version: '3.9'


services:
  
  chat-service-db:
    image: mysql:5.7.20
    container_name: chat-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "7200:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - chat-service-db
    links:
      - chat-service-db
    restart: always
    ports:
      - 7300:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php


volumes:
  dbdata:
  chat-service-db:
