version: '3.9'


services:
  
  chat-service-db:
    image: mysql:5.7.20
    container_name: chat-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "7200:3306"
    volumes:
      - chat-service-db:/var/lib/mysql

  users-service-db:
    image: mysql:5.7.20
    container_name: users-service-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - "7201:3306"
    volumes:
      - users-service-db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - chat-service-db
      - users-service-db
    links:
      - chat-service-db
      - users-service-db
    restart: always
    ports:
      - 7300:80
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  chat-service:
    container_name: chat-service
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    volumes:
      - ./trabalho_individual/chat-service:/chat-service
    ports:
      - "7100:7100"
    depends_on:
      - chat-service-db

  users-service:
    container_name: users-service
    build:
      context: ./users-service
      dockerfile: Dockerfile
    volumes:
      - ./trabalho_individual/users-service:/users-service
    ports:
      - "7101:7101"
    depends_on:
      - users-service-db

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    volumes:
      - ./trabalho_individual/api-gateway:/api-gateway
    ports:
      - "7000:7000"
    depends_on:
      - chat-service-db
      - users-service-db


volumes:
  chat-service-db:
  users-service-db:
